/**
Autor: Marcos Chavarria Fallas
Fecha: 02/04/2019
Privilegios y accesos
*/
GRANT SELECT, INSERT, DELETE, UPDATE ON GEA_WEB.LECTURA TO 'GEA_CON';
GRANT SELECT, INSERT, DELETE, UPDATE ON GEA_WEB.LECTURA_DIARIA TO 'GEA_CON';
GRANT SELECT, INSERT, DELETE, UPDATE ON GEA_WEB.MEDIDOR TO 'GEA_CON';
